import { randomBytes, createHash } from "node:crypto";
import { and, asc, eq, or } from "drizzle-orm";
import { db } from "@/db/client";
import { businesses, serviceWaitlist, services } from "@/db/schema";
import { ensureServicePricingSchema } from "./ensure-service-pricing-schema";
import { sendWaitlistOfferEmail } from "./staff-invitations";

export const hashWaitlistToken=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function offerNextWaitlist(input:{businessId:string;serviceId:string;staffId:string;startsAt:Date}){await ensureServicePricingSchema();const[business]=await db.select({timezone:businesses.timezone}).from(businesses).where(eq(businesses.id,input.businessId)).limit(1);if(!business)return false;const requestedDay=new Intl.DateTimeFormat("en-CA",{timeZone:business.timezone}).format(input.startsAt);const[row]=await db.select({id:serviceWaitlist.id,email:serviceWaitlist.email,startsAt:serviceWaitlist.startsAt,staffId:serviceWaitlist.staffId,anyStaff:serviceWaitlist.anyStaff,serviceName:services.name,businessName:businesses.name,timezone:businesses.timezone,minutes:services.waitlistConfirmationMinutes}).from(serviceWaitlist).innerJoin(services,eq(services.id,serviceWaitlist.serviceId)).innerJoin(businesses,eq(businesses.id,serviceWaitlist.businessId)).where(and(eq(serviceWaitlist.businessId,input.businessId),eq(serviceWaitlist.serviceId,input.serviceId),eq(serviceWaitlist.status,"WAITING"),or(and(eq(serviceWaitlist.staffId,input.staffId),eq(serviceWaitlist.startsAt,input.startsAt)),and(eq(serviceWaitlist.requestedDay,requestedDay),or(eq(serviceWaitlist.anyStaff,true),eq(serviceWaitlist.staffId,input.staffId)))))).orderBy(asc(serviceWaitlist.createdAt)).limit(1);if(!row)return false;const token=randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+row.minutes*60_000);const[claimed]=await db.update(serviceWaitlist).set({status:"OFFERED",staffId:input.staffId,startsAt:input.startsAt,anyStaff:false,offerTokenHash:hashWaitlistToken(token),offerExpiresAt:expiresAt,offeredAt:new Date(),updatedAt:new Date()}).where(and(eq(serviceWaitlist.id,row.id),eq(serviceWaitlist.status,"WAITING"))).returning({id:serviceWaitlist.id});if(!claimed)return false;const sent=await sendWaitlistOfferEmail({email:row.email,businessName:row.businessName,serviceName:row.serviceName,startsAt:input.startsAt,timezone:row.timezone,token,expiresAt});if(!sent)await db.update(serviceWaitlist).set({status:"WAITING",staffId:row.staffId,startsAt:row.startsAt,anyStaff:row.anyStaff,offerTokenHash:null,offerExpiresAt:null,offeredAt:null,updatedAt:new Date()}).where(eq(serviceWaitlist.id,row.id));return sent;}
