import { randomBytes, createHash } from "node:crypto";
import { and, asc, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { businesses, serviceWaitlist, services } from "@/db/schema";
import { ensureServicePricingSchema } from "./ensure-service-pricing-schema";
import { sendWaitlistOfferEmail } from "./staff-invitations";

export const hashWaitlistToken=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function offerNextWaitlist(input:{businessId:string;serviceId:string;staffId:string;startsAt:Date}){await ensureServicePricingSchema();const[row]=await db.select({id:serviceWaitlist.id,email:serviceWaitlist.email,startsAt:serviceWaitlist.startsAt,serviceName:services.name,businessName:businesses.name,timezone:businesses.timezone,minutes:services.waitlistConfirmationMinutes}).from(serviceWaitlist).innerJoin(services,eq(services.id,serviceWaitlist.serviceId)).innerJoin(businesses,eq(businesses.id,serviceWaitlist.businessId)).where(and(eq(serviceWaitlist.businessId,input.businessId),eq(serviceWaitlist.serviceId,input.serviceId),eq(serviceWaitlist.staffId,input.staffId),eq(serviceWaitlist.startsAt,input.startsAt),eq(serviceWaitlist.status,"WAITING"))).orderBy(asc(serviceWaitlist.createdAt)).limit(1);if(!row)return false;const token=randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+row.minutes*60_000);const[claimed]=await db.update(serviceWaitlist).set({status:"OFFERED",offerTokenHash:hashWaitlistToken(token),offerExpiresAt:expiresAt,offeredAt:new Date(),updatedAt:new Date()}).where(and(eq(serviceWaitlist.id,row.id),eq(serviceWaitlist.status,"WAITING"))).returning({id:serviceWaitlist.id});if(!claimed)return false;const sent=await sendWaitlistOfferEmail({email:row.email,businessName:row.businessName,serviceName:row.serviceName,startsAt:row.startsAt,timezone:row.timezone,token,expiresAt});if(!sent)await db.update(serviceWaitlist).set({status:"WAITING",offerTokenHash:null,offerExpiresAt:null,offeredAt:null,updatedAt:new Date()}).where(eq(serviceWaitlist.id,row.id));return sent;}
