"use client";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { changeAppointmentStatus, createAppointment, rescheduleAppointment } from "./actions";

type Staff={id:string;name:string}; type Service={staffId:string;id:string;name:string;duration:number}; type Entry={id:string;startsAt:string;endsAt:string;status:string;serviceName:string;customerName:string;staffId:string;staffName:string;notes:string|null}; type Data={startDate:string;timezone:string;canManage:boolean;staff:Staff[];catalog:Service[];entries:Entry[]};
const labels:Record<string,string>={BOOKED:"Prenotato",CONFIRMED:"Confermato",ARRIVED:"Arrivato",COMPLETED:"Eseguito",CANCELLED:"Cancellato",NO_SHOW:"Non presentato"};
const ownerNext:Record<string,string[]>={BOOKED:["CONFIRMED","CANCELLED","NO_SHOW"],CONFIRMED:["ARRIVED","COMPLETED","CANCELLED","NO_SHOW"],ARRIVED:["COMPLETED","CANCELLED","NO_SHOW"]};
const shift=(date:string,days:number)=>{const [y,m,d]=date.split("-").map(Number);return new Date(Date.UTC(y,m-1,d+days)).toISOString().slice(0,10)};
const dayName=(date:string)=>new Intl.DateTimeFormat("it-IT",{timeZone:"UTC",weekday:"long",day:"numeric",month:"long"}).format(new Date(`${date}T12:00:00Z`));
const stamp=(value:string,zone:string)=>new Intl.DateTimeFormat("sv-SE",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value)).replace(" ","T");

export function AgendaCalendar({today,canManage}:{today:string;canManage:boolean}){
 const router=useRouter(),q=useSearchParams(); const [date,setDate]=useState(/^\d{4}-\d{2}-\d{2}$/.test(q.get("date")??"")?q.get("date")!:today),[view,setView]=useState(q.get("view")==="week"?"week":"day"),[data,setData]=useState<Data>(),[open,setOpen]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");const r=await fetch(`/api/agenda?date=${date}&view=${view}`,{cache:"no-store"});if(!r.ok){setError("Impossibile caricare l’agenda.");return}setData(await r.json())},[date,view]); useEffect(()=>{void load()},[load]); useEffect(()=>{router.replace(`/app/agenda?date=${date}&view=${view}`,{scroll:false})},[date,view,router]);
 const time=(v:string)=>new Intl.DateTimeFormat("it-IT",{timeZone:data?.timezone,hour:"2-digit",minute:"2-digit"}).format(new Date(v)); const dateOf=(v:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:data?.timezone}).format(new Date(v)); const refresh=()=>void load();
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await createAppointment(new FormData(e.currentTarget));setOpen(false);refresh()}catch{setError("Impossibile creare l’appuntamento.")}}
 async function status(id:string,value:string){const f=new FormData();f.set("id",id);f.set("status",value);try{await changeAppointmentStatus(f);refresh()}catch{setError("Stato non aggiornato.")}}
 async function reschedule(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await rescheduleAppointment(new FormData(e.currentTarget));refresh()}catch{setError("Spostamento non possibile: controlla la disponibilità.")}}
 const card=(item:Entry)=>{const terminal=["COMPLETED","CANCELLED","NO_SHOW"].includes(item.status);const options=canManage?(ownerNext[item.status]??[]):terminal?[]:["COMPLETED","CANCELLED","NO_SHOW"];return <article className={`agenda-appointment status-${item.status.toLowerCase()}`} key={item.id}><span>{time(item.startsAt)}</span><strong>{item.customerName}</strong><small>{item.serviceName} · {item.staffName}</small><em>{labels[item.status]??item.status}</em>{options.length?<select defaultValue="" onChange={e=>e.target.value&&void status(item.id,e.target.value)}><option value="" disabled>Stato…</option>{options.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select>:null}{!terminal&&data?<details className="agenda-reschedule"><summary>Sposta data e ora</summary><form onSubmit={reschedule}><input type="hidden" name="id" value={item.id}/><input name="startsAt" type="datetime-local" defaultValue={stamp(item.startsAt,data.timezone)} required/><button className="ghost-button">Salva</button></form></details>:null}</article>};
 if(!data)return <div className="empty-state">Caricamento agenda…</div>;
 const days=view==="week"?Array.from({length:7},(_,i)=>shift(data.startDate,i)):[date];
 return <><div className="agenda-toolbar"><div className="agenda-navigation"><button className="agenda-icon-button" onClick={()=>setDate(shift(date,view==="week"?-7:-1))}>←</button><button className="ghost-button" onClick={()=>setDate(today)}>Oggi</button><button className="agenda-icon-button" onClick={()=>setDate(shift(date,view==="week"?7:1))}>→</button></div><h2>{view==="day"?dayName(date):`Settimana dal ${dayName(data.startDate)}`}</h2><div className="agenda-view-switch"><button className={view==="day"?"active":""} onClick={()=>setView("day")}>Giorno</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>Settimana</button></div></div>{error?<p className="form-error agenda-error">{error}</p>:null}<div className={view==="week"?"week-calendar":"agenda-scroll"}>{days.map(day=><section className={view==="week"?(day===today?"week-day today":"week-day"):"agenda-day"} key={day}><header><strong>{dayName(day)}</strong></header>{data.entries.filter(x=>dateOf(x.startsAt)===day).length?data.entries.filter(x=>dateOf(x.startsAt)===day).map(card):<p className="muted">Nessun appuntamento.</p>}</section>)}</div>{canManage?<button className="new-booking-fab" onClick={()=>setOpen(true)}><span>＋</span> Nuova prenotazione</button>:null}{open?<div className="booking-modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="booking-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(false)}>×</button><h2>Nuova prenotazione</h2><form className="compact-form stacked" onSubmit={create}><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><input name="customerName" placeholder="Nome cliente" required minLength={2}/><div className="form-row"><input name="email" type="email" placeholder="Email"/><input name="phone" type="tel" placeholder="Telefono"/></div><label>Operatore<select name="staffId">{data.staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Servizio<select name="serviceId">{data.catalog.map(s=><option value={s.id} key={`${s.staffId}-${s.id}`}>{s.name} · {s.duration} min</option>)}</select></label><label>Data e ora<input name="startsAt" type="datetime-local" defaultValue={`${date}T09:00`} required/></label><textarea name="notes" placeholder="Note (opzionali)"/><button className="primary-button">Conferma prenotazione</button></form></section></div>:null}</>;
}
