import { asc, eq } from "drizzle-orm";
import Link from "next/link";
import { notFound } from "next/navigation";
import { LogoutButton } from "@/app/app/logout-button";
import { db } from "@/db/client";
import { businessMemberships, businesses, services, staffMembers, users } from "@/db/schema";
import { requireSuperAdmin } from "@/lib/super-admin";
import { setLicenseStatus } from "../actions";
export default async function LicenseDetailPage({ params }: { params: Promise<{ businessId: string }> }) {
  await requireSuperAdmin(); const { businessId } = await params; const [business] = await db.select().from(businesses).where(eq(businesses.id,businessId)).limit(1); if(!business) notFound();
  const [members,operators,serviceRows]=await Promise.all([db.select({id:businessMemberships.id,role:businessMemberships.role,email:users.email,name:users.name,createdAt:businessMemberships.createdAt}).from(businessMemberships).innerJoin(users,eq(users.id,businessMemberships.userId)).where(eq(businessMemberships.businessId,businessId)).orderBy(asc(users.email)),db.select({id:staffMembers.id,name:staffMembers.name,title:staffMembers.title,active:staffMembers.active,email:users.email}).from(staffMembers).leftJoin(users,eq(users.id,staffMembers.userId)).where(eq(staffMembers.businessId,businessId)).orderBy(asc(staffMembers.name)),db.select({id:services.id,name:services.name,active:services.active,onlineBookable:services.onlineBookable}).from(services).where(eq(services.businessId,businessId)).orderBy(asc(services.name))]);
  return <main className="dashboard-shell"><header className="app-header"><div><p className="eyebrow">Controllo licenza</p><strong>{business.name}</strong></div><LogoutButton/></header><nav className="app-nav"><Link href="/admin/licenses">← Tutte le licenze</Link></nav><section className="page-heading"><div><p className="eyebrow">Licenza {business.active ? "attiva" : "disattivata"}</p><h1>{business.name}</h1></div><div className="button-row"><span className="status-pill">{business.active ? "Attiva" : "Disattivata"}</span><form action={setLicenseStatus}><input type="hidden" name="businessId" value={business.id}/><input type="hidden" name="active" value={String(!business.active)}/><button className={business.active ? "danger-button" : "primary-button"}>{business.active ? "Disattiva licenza" : "Riattiva licenza"}</button></form></div></section><section className="management-grid"><article className="panel"><h2>Dati licenza</h2><p><strong>ID:</strong> {business.id}</p><p><strong>Slug:</strong> {business.slug}</p><p><strong>Fuso orario:</strong> {business.timezone}</p></article><article className="panel"><h2>Riepilogo</h2><p><strong>{members.length}</strong> account · <strong>{operators.length}</strong> operatori · <strong>{serviceRows.length}</strong> servizi</p></article></section><section className="list-section"><h2>Titolari e account staff</h2><div className="data-list">{members.map(m=><article className="data-row" key={m.id}><div><p className="eyebrow">{m.role}</p><h3>{m.name||"Senza nome"}</h3><p>{m.email}</p></div></article>)}</div></section><section className="list-section"><h2>Operatori</h2><div className="data-list">{operators.map(o=><article className="data-row" key={o.id}><div><h3>{o.name}</h3><p>{o.title||"Operatore"}</p><p className="muted">{o.email||"Account non ancora collegato"}</p></div><span className="status-pill">{o.active?"Attivo":"Disattivo"}</span></article>)}</div></section><section className="list-section"><h2>Servizi</h2><div className="data-list">{serviceRows.map(s=><article className="data-row" key={s.id}><div><h3>{s.name}</h3><p className="muted">{s.onlineBookable?"Prenotabile online":"Solo gestionale"}</p></div><span className="status-pill">{s.active?"Attivo":"Disattivo"}</span></article>)}</div></section></main>;
}
