"use server";
import { and,eq,sql } from "drizzle-orm"; import { revalidatePath } from "next/cache"; import { z } from "zod"; import { db } from "@/db/client"; import { inventoryCategories,inventoryCategoryServiceCategories,inventoryCategoryServices,inventoryMovements,inventoryProducts,inventoryProductServices,serviceCategories,services } from "@/db/schema"; import { requireBusinessContext } from "@/lib/business-context"; import { ensureInventorySchema } from "@/lib/ensure-inventory-schema";
async function owner(){const c=await requireBusinessContext();if(c.role!=="OWNER"||!c.modules.includes("INVENTORY"))throw Error("Modulo magazzino non attivo.");await ensureInventorySchema();return c;}
export async function createInventoryCategory(f:FormData){const c=await owner();const name=z.string().trim().min(2).max(80).parse(f.get("name"));await db.insert(inventoryCategories).values({businessId:c.businessId,name});revalidatePath("/app/inventory");}
export async function createProduct(f:FormData){const c=await owner();const i=z.object({categoryId:z.string().uuid(),name:z.string().trim().min(2),sku:z.string().trim().max(60).optional(),price:z.coerce.number().min(0),stock:z.coerce.number().int().min(0),minimum:z.coerce.number().int().min(0)}).parse({categoryId:f.get("categoryId"),name:f.get("name"),sku:f.get("sku")||undefined,price:f.get("price"),stock:f.get("stock"),minimum:f.get("minimum")});const[category]=await db.select({id:inventoryCategories.id}).from(inventoryCategories).where(and(eq(inventoryCategories.id,i.categoryId),eq(inventoryCategories.businessId,c.businessId)));if(!category)throw Error("Categoria articoli non valida.");const[p]=await db.insert(inventoryProducts).values({businessId:c.businessId,...i,salePrice:i.price.toFixed(2),minimumStock:i.minimum}).returning({id:inventoryProducts.id});if(i.stock)await db.insert(inventoryMovements).values({businessId:c.businessId,productId:p.id,quantity:i.stock,reason:"CARICO_INIZIALE"});revalidatePath("/app/inventory");}
export async function moveStock(f:FormData){const c=await owner();const i=z.object({id:z.string().uuid(),quantity:z.coerce.number().int().positive(),reason:z.enum(["CARICO","SCARICO","VENDITA"]),note:z.string().trim().max(160).optional()}).parse({id:f.get("id"),quantity:f.get("quantity"),reason:f.get("reason"),note:f.get("note")||undefined});const delta=i.reason==="CARICO"?i.quantity:-i.quantity;const[p]=await db.select({stock:inventoryProducts.stock}).from(inventoryProducts).where(and(eq(inventoryProducts.id,i.id),eq(inventoryProducts.businessId,c.businessId)));if(!p||p.stock+delta<0)throw Error("Giacenza insufficiente.");await db.transaction(async tx=>{await tx.update(inventoryProducts).set({stock:sql`${inventoryProducts.stock} + ${delta}`,updatedAt:new Date()}).where(and(eq(inventoryProducts.id,i.id),eq(inventoryProducts.businessId,c.businessId)));await tx.insert(inventoryMovements).values({businessId:c.businessId,productId:i.id,quantity:delta,reason:i.reason,note:i.note});});revalidatePath("/app/inventory");}
export async function linkService(f:FormData){const c=await owner();const i=z.object({productId:z.string().uuid(),serviceId:z.string().uuid(),quantity:z.coerce.number().int().min(1)}).parse({productId:f.get("productId"),serviceId:f.get("serviceId"),quantity:f.get("quantity")});const[s]=await db.select({id:services.id}).from(services).where(and(eq(services.id,i.serviceId),eq(services.businessId,c.businessId)));if(!s)throw Error("Servizio non valido.");await db.insert(inventoryProductServices).values({businessId:c.businessId,...i}).onConflictDoUpdate({target:[inventoryProductServices.productId,inventoryProductServices.serviceId],set:{quantity:i.quantity}});revalidatePath("/app/inventory");}
export async function linkCategoryToService(f:FormData){const c=await owner();const i=z.object({inventoryCategoryId:z.string().uuid(),serviceId:z.string().uuid()}).parse({inventoryCategoryId:f.get("inventoryCategoryId"),serviceId:f.get("serviceId")});await db.insert(inventoryCategoryServices).values({businessId:c.businessId,...i}).onConflictDoNothing();revalidatePath("/app/inventory");}
export async function linkCategoryToServiceCategory(f:FormData){const c=await owner();const i=z.object({inventoryCategoryId:z.string().uuid(),serviceCategoryId:z.string().uuid()}).parse({inventoryCategoryId:f.get("inventoryCategoryId"),serviceCategoryId:f.get("serviceCategoryId")});const[valid]=await db.select({id:serviceCategories.id}).from(serviceCategories).where(and(eq(serviceCategories.id,i.serviceCategoryId),eq(serviceCategories.businessId,c.businessId)));if(!valid)throw Error("Categoria servizi non valida.");await db.insert(inventoryCategoryServiceCategories).values({businessId:c.businessId,...i}).onConflictDoNothing();revalidatePath("/app/inventory");}
