import { and, desc, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { db } from "@/db/client";
import { appointments, staffMembers } from "@/db/schema";
import { requireBusinessContext } from "@/lib/business-context";
import { AppNav } from "../app-nav";

export default async function StatisticsPage(){
  const context=await requireBusinessContext(); if(context.role!=="OWNER")redirect("/app/agenda");
  const rows=await db.select({price:appointments.price,startsAt:appointments.startsAt,service:appointments.serviceName,staff:staffMembers.name,staffId:staffMembers.id}).from(appointments).innerJoin(staffMembers,and(eq(appointments.staffId,staffMembers.id),eq(staffMembers.businessId,context.businessId))).where(and(eq(appointments.businessId,context.businessId),eq(appointments.status,"COMPLETED"))).orderBy(desc(appointments.startsAt));
  const total=rows.reduce((sum,x)=>sum+Number(x.price),0);const thisMonth=new Intl.DateTimeFormat("en-CA",{timeZone:context.timezone,year:"numeric",month:"2-digit"}).format(new Date());const monthly=rows.filter(x=>new Intl.DateTimeFormat("en-CA",{timeZone:context.timezone,year:"numeric",month:"2-digit"}).format(x.startsAt)===thisMonth);const staff=Object.values(rows.reduce<Record<string,{name:string;count:number;amount:number}>>((m,x)=>{m[x.staffId]??={name:x.staff,count:0,amount:0};m[x.staffId].count++;m[x.staffId].amount+=Number(x.price);return m},{})).sort((a,b)=>b.amount-a.amount);const services=Object.values(rows.reduce<Record<string,{name:string;count:number;amount:number}>>((m,x)=>{m[x.service]??={name:x.service,count:0,amount:0};m[x.service].count++;m[x.service].amount+=Number(x.price);return m},{})).sort((a,b)=>b.amount-a.amount);
  return <main className="dashboard-shell"><AppNav businessName={context.businessName} role={context.role}/><div className="page-heading"><div><p className="eyebrow">Titolare</p><h1>Statistiche e incassi</h1></div><p className="muted">Solo appuntamenti eseguiti.</p></div><section className="module-grid"><article className="module-card"><h2>€ {total.toFixed(2)}</h2><p>Incasso totale</p></article><article className="module-card"><h2>€ {monthly.reduce((s,x)=>s+Number(x.price),0).toFixed(2)}</h2><p>Incasso mese corrente</p></article><article className="module-card"><h2>{rows.length}</h2><p>Servizi eseguiti</p></article><article className="module-card"><h2>€ {rows.length?(total/rows.length).toFixed(2):"0.00"}</h2><p>Scontrino medio</p></article></section><section className="management-grid"><article className="panel"><h2>Incassi per operatore</h2>{staff.length?staff.map(x=><p key={x.name}><strong>{x.name}</strong><br/><span className="muted">€ {x.amount.toFixed(2)} · {x.count} servizi</span></p>):<p className="muted">Nessun incasso ancora.</p>}</article><article className="panel"><h2>Servizi più richiesti</h2>{services.slice(0,8).map(x=><p key={x.name}><strong>{x.name}</strong><br/><span className="muted">€ {x.amount.toFixed(2)} · {x.count} eseguiti</span></p>)}</article></section></main>
}
